/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VantagensFiscaisRouteImport } from './routes/vantagens-fiscais'
import { Route as TestemunhosRouteImport } from './routes/testemunhos'
import { Route as TermosECondicoesRouteImport } from './routes/termos-e-condicoes'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SistemaConstrutivoRouteImport } from './routes/sistema-construtivo'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EquipaRouteImport } from './routes/equipa'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AntesDepoisRouteImport } from './routes/antes-depois'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicosIndexRouteImport } from './routes/servicos.index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as ProjetosListaRouteImport } from './routes/projetos.lista'
import { Route as ProjetosFiltroRouteImport } from './routes/projetos.filtro'
import { Route as ProjetosFancyFiltroRouteImport } from './routes/projetos.fancy-filtro'
import { Route as ProjetosFancyRouteImport } from './routes/projetos.fancy'
import { Route as ProjetosSlugRouteImport } from './routes/projetos.$slug'
import { Route as GaleriaMasonryRouteImport } from './routes/galeria.masonry'

const VantagensFiscaisRoute = VantagensFiscaisRouteImport.update({
  id: '/vantagens-fiscais',
  path: '/vantagens-fiscais',
  getParentRoute: () => rootRouteImport,
} as any)
const TestemunhosRoute = TestemunhosRouteImport.update({
  id: '/testemunhos',
  path: '/testemunhos',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosECondicoesRoute = TermosECondicoesRouteImport.update({
  id: '/termos-e-condicoes',
  path: '/termos-e-condicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemaConstrutivoRoute = SistemaConstrutivoRouteImport.update({
  id: '/sistema-construtivo',
  path: '/sistema-construtivo',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipaRoute = EquipaRouteImport.update({
  id: '/equipa',
  path: '/equipa',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AntesDepoisRoute = AntesDepoisRouteImport.update({
  id: '/antes-depois',
  path: '/antes-depois',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosIndexRoute = ServicosIndexRouteImport.update({
  id: '/servicos/',
  path: '/servicos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosListaRoute = ProjetosListaRouteImport.update({
  id: '/projetos/lista',
  path: '/projetos/lista',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosFiltroRoute = ProjetosFiltroRouteImport.update({
  id: '/projetos/filtro',
  path: '/projetos/filtro',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosFancyFiltroRoute = ProjetosFancyFiltroRouteImport.update({
  id: '/projetos/fancy-filtro',
  path: '/projetos/fancy-filtro',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosFancyRoute = ProjetosFancyRouteImport.update({
  id: '/projetos/fancy',
  path: '/projetos/fancy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosSlugRoute = ProjetosSlugRouteImport.update({
  id: '/projetos/$slug',
  path: '/projetos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaMasonryRoute = GaleriaMasonryRouteImport.update({
  id: '/masonry',
  path: '/masonry',
  getParentRoute: () => GaleriaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/antes-depois': typeof AntesDepoisRoute
  '/blog': typeof BlogRoute
  '/contacto': typeof ContactoRoute
  '/empresa': typeof EmpresaRoute
  '/equipa': typeof EquipaRoute
  '/faq': typeof FaqRoute
  '/galeria': typeof GaleriaRouteWithChildren
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/precos': typeof PrecosRoute
  '/sistema-construtivo': typeof SistemaConstrutivoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-e-condicoes': typeof TermosECondicoesRoute
  '/testemunhos': typeof TestemunhosRoute
  '/vantagens-fiscais': typeof VantagensFiscaisRoute
  '/galeria/masonry': typeof GaleriaMasonryRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/projetos/fancy': typeof ProjetosFancyRoute
  '/projetos/fancy-filtro': typeof ProjetosFancyFiltroRoute
  '/projetos/filtro': typeof ProjetosFiltroRoute
  '/projetos/lista': typeof ProjetosListaRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/servicos/': typeof ServicosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/antes-depois': typeof AntesDepoisRoute
  '/blog': typeof BlogRoute
  '/contacto': typeof ContactoRoute
  '/empresa': typeof EmpresaRoute
  '/equipa': typeof EquipaRoute
  '/faq': typeof FaqRoute
  '/galeria': typeof GaleriaRouteWithChildren
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/precos': typeof PrecosRoute
  '/sistema-construtivo': typeof SistemaConstrutivoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-e-condicoes': typeof TermosECondicoesRoute
  '/testemunhos': typeof TestemunhosRoute
  '/vantagens-fiscais': typeof VantagensFiscaisRoute
  '/galeria/masonry': typeof GaleriaMasonryRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/projetos/fancy': typeof ProjetosFancyRoute
  '/projetos/fancy-filtro': typeof ProjetosFancyFiltroRoute
  '/projetos/filtro': typeof ProjetosFiltroRoute
  '/projetos/lista': typeof ProjetosListaRoute
  '/projetos': typeof ProjetosIndexRoute
  '/servicos': typeof ServicosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/antes-depois': typeof AntesDepoisRoute
  '/blog': typeof BlogRoute
  '/contacto': typeof ContactoRoute
  '/empresa': typeof EmpresaRoute
  '/equipa': typeof EquipaRoute
  '/faq': typeof FaqRoute
  '/galeria': typeof GaleriaRouteWithChildren
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/precos': typeof PrecosRoute
  '/sistema-construtivo': typeof SistemaConstrutivoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-e-condicoes': typeof TermosECondicoesRoute
  '/testemunhos': typeof TestemunhosRoute
  '/vantagens-fiscais': typeof VantagensFiscaisRoute
  '/galeria/masonry': typeof GaleriaMasonryRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/projetos/fancy': typeof ProjetosFancyRoute
  '/projetos/fancy-filtro': typeof ProjetosFancyFiltroRoute
  '/projetos/filtro': typeof ProjetosFiltroRoute
  '/projetos/lista': typeof ProjetosListaRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/servicos/': typeof ServicosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/antes-depois'
    | '/blog'
    | '/contacto'
    | '/empresa'
    | '/equipa'
    | '/faq'
    | '/galeria'
    | '/politica-de-privacidade'
    | '/precos'
    | '/sistema-construtivo'
    | '/sitemap.xml'
    | '/termos-e-condicoes'
    | '/testemunhos'
    | '/vantagens-fiscais'
    | '/galeria/masonry'
    | '/projetos/$slug'
    | '/projetos/fancy'
    | '/projetos/fancy-filtro'
    | '/projetos/filtro'
    | '/projetos/lista'
    | '/projetos/'
    | '/servicos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/antes-depois'
    | '/blog'
    | '/contacto'
    | '/empresa'
    | '/equipa'
    | '/faq'
    | '/galeria'
    | '/politica-de-privacidade'
    | '/precos'
    | '/sistema-construtivo'
    | '/sitemap.xml'
    | '/termos-e-condicoes'
    | '/testemunhos'
    | '/vantagens-fiscais'
    | '/galeria/masonry'
    | '/projetos/$slug'
    | '/projetos/fancy'
    | '/projetos/fancy-filtro'
    | '/projetos/filtro'
    | '/projetos/lista'
    | '/projetos'
    | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/antes-depois'
    | '/blog'
    | '/contacto'
    | '/empresa'
    | '/equipa'
    | '/faq'
    | '/galeria'
    | '/politica-de-privacidade'
    | '/precos'
    | '/sistema-construtivo'
    | '/sitemap.xml'
    | '/termos-e-condicoes'
    | '/testemunhos'
    | '/vantagens-fiscais'
    | '/galeria/masonry'
    | '/projetos/$slug'
    | '/projetos/fancy'
    | '/projetos/fancy-filtro'
    | '/projetos/filtro'
    | '/projetos/lista'
    | '/projetos/'
    | '/servicos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AntesDepoisRoute: typeof AntesDepoisRoute
  BlogRoute: typeof BlogRoute
  ContactoRoute: typeof ContactoRoute
  EmpresaRoute: typeof EmpresaRoute
  EquipaRoute: typeof EquipaRoute
  FaqRoute: typeof FaqRoute
  GaleriaRoute: typeof GaleriaRouteWithChildren
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  PrecosRoute: typeof PrecosRoute
  SistemaConstrutivoRoute: typeof SistemaConstrutivoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosECondicoesRoute: typeof TermosECondicoesRoute
  TestemunhosRoute: typeof TestemunhosRoute
  VantagensFiscaisRoute: typeof VantagensFiscaisRoute
  ProjetosSlugRoute: typeof ProjetosSlugRoute
  ProjetosFancyRoute: typeof ProjetosFancyRoute
  ProjetosFancyFiltroRoute: typeof ProjetosFancyFiltroRoute
  ProjetosFiltroRoute: typeof ProjetosFiltroRoute
  ProjetosListaRoute: typeof ProjetosListaRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
  ServicosIndexRoute: typeof ServicosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vantagens-fiscais': {
      id: '/vantagens-fiscais'
      path: '/vantagens-fiscais'
      fullPath: '/vantagens-fiscais'
      preLoaderRoute: typeof VantagensFiscaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testemunhos': {
      id: '/testemunhos'
      path: '/testemunhos'
      fullPath: '/testemunhos'
      preLoaderRoute: typeof TestemunhosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-e-condicoes': {
      id: '/termos-e-condicoes'
      path: '/termos-e-condicoes'
      fullPath: '/termos-e-condicoes'
      preLoaderRoute: typeof TermosECondicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistema-construtivo': {
      id: '/sistema-construtivo'
      path: '/sistema-construtivo'
      fullPath: '/sistema-construtivo'
      preLoaderRoute: typeof SistemaConstrutivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipa': {
      id: '/equipa'
      path: '/equipa'
      fullPath: '/equipa'
      preLoaderRoute: typeof EquipaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antes-depois': {
      id: '/antes-depois'
      path: '/antes-depois'
      fullPath: '/antes-depois'
      preLoaderRoute: typeof AntesDepoisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/': {
      id: '/servicos/'
      path: '/servicos'
      fullPath: '/servicos/'
      preLoaderRoute: typeof ServicosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/lista': {
      id: '/projetos/lista'
      path: '/projetos/lista'
      fullPath: '/projetos/lista'
      preLoaderRoute: typeof ProjetosListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/filtro': {
      id: '/projetos/filtro'
      path: '/projetos/filtro'
      fullPath: '/projetos/filtro'
      preLoaderRoute: typeof ProjetosFiltroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/fancy-filtro': {
      id: '/projetos/fancy-filtro'
      path: '/projetos/fancy-filtro'
      fullPath: '/projetos/fancy-filtro'
      preLoaderRoute: typeof ProjetosFancyFiltroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/fancy': {
      id: '/projetos/fancy'
      path: '/projetos/fancy'
      fullPath: '/projetos/fancy'
      preLoaderRoute: typeof ProjetosFancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$slug': {
      id: '/projetos/$slug'
      path: '/projetos/$slug'
      fullPath: '/projetos/$slug'
      preLoaderRoute: typeof ProjetosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria/masonry': {
      id: '/galeria/masonry'
      path: '/masonry'
      fullPath: '/galeria/masonry'
      preLoaderRoute: typeof GaleriaMasonryRouteImport
      parentRoute: typeof GaleriaRoute
    }
  }
}

interface GaleriaRouteChildren {
  GaleriaMasonryRoute: typeof GaleriaMasonryRoute
}

const GaleriaRouteChildren: GaleriaRouteChildren = {
  GaleriaMasonryRoute: GaleriaMasonryRoute,
}

const GaleriaRouteWithChildren =
  GaleriaRoute._addFileChildren(GaleriaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AntesDepoisRoute: AntesDepoisRoute,
  BlogRoute: BlogRoute,
  ContactoRoute: ContactoRoute,
  EmpresaRoute: EmpresaRoute,
  EquipaRoute: EquipaRoute,
  FaqRoute: FaqRoute,
  GaleriaRoute: GaleriaRouteWithChildren,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  PrecosRoute: PrecosRoute,
  SistemaConstrutivoRoute: SistemaConstrutivoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosECondicoesRoute: TermosECondicoesRoute,
  TestemunhosRoute: TestemunhosRoute,
  VantagensFiscaisRoute: VantagensFiscaisRoute,
  ProjetosSlugRoute: ProjetosSlugRoute,
  ProjetosFancyRoute: ProjetosFancyRoute,
  ProjetosFancyFiltroRoute: ProjetosFancyFiltroRoute,
  ProjetosFiltroRoute: ProjetosFiltroRoute,
  ProjetosListaRoute: ProjetosListaRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
  ServicosIndexRoute: ServicosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
